---

- name: install caffeine
  block:
    - homebrew_cask:
        name: caffeine
        state: present
      when: ansible_os_family == 'Darwin'

    - apt:
        name: caffeine
        state: present
      when: ansible_os_family == 'Debian'
